### ISSUE TITLE
DateTime default value

### ISSUE THREAD

**Issue by matthewmueller** [standardschema/javascript#31]
Looks like this doesn't work:

``` js
now: new Types.DateTime({
    default: new Date()
})
```

Leads to:

```
TypeError: Value argument must be a reference or primitive value
```

Guessing it's related to default being on the Any time, but DateTime being more specific.

**Comment by blakeembrey** [comment]
Thanks. I don't have a great solution when it comes to live dates (I'm assuming what you wanted was more like a `Date.now` functionality?). I'm thinking the best solution may be to use a reference to known URIs/objects/functions that when seen in different contexts can be serialised appropriately (E.g. into a data schema format, you can't use functions). Namely, so that it could serialise to a database date method or to JavaScript, etc.
